@baseUri = http://localhost:8182/api

### Listar todos os customers
GET {{baseUri}}/customers HTTP/1.1
Content-Type: application/json


### Criar um novo customer
POST {{baseUri}}/customers HTTP/1.1
Content-Type: application/json

{
  "name": "customer novo",
  "email": "customer@seilaaaa.com",
  "phone": "123456789"
}


### Buscar um customer por ID
GET {{baseUri}}/customers/1 HTTP/1.1
Content-Type: application/json

### Atualizar um customer existente
PUT {{baseUri}}/customers/3 HTTP/1.1
Content-Type: application/json

{
  "name": "customer novo",
  "email": "customer@exemplooooooooo.com",
  "phone": "123456789"
}

### Deletar um customer
DELETE {{baseUri}}/customers/22 HTTP/1.1
Content-Type: application/json
